sudo: required

services:
  - docker

script:
  - pwd
  - ls -al
  - export DEBIAN_FRONTEND=noninteractive
  - git clone --depth=50 --branch=master https://github.  - com/beevelop/docker-wordpress.git beevelop/docker-wordpress
  - pwd
  - ls -al
  - cd beevelop/docker-wordpress
  - git checkout -qf fb0b8bef2147b1b7c1b3c34e05eb5016cadb5e80
  - sudo service docker start
  - rvm use default
  - ruby --version
  - rvm --version
  - bundle --version
  - gem --version
  - docker build -t wp .
  - docker run -d -e MYSQL_ROOT_PASSWORD=Un1c0rn --name mysql mysql
  - docker run -d -e WORDPRESS_PLUGINS="jetpack;wordfence" -e WORDPRESS_ACTIVE_THEME=responsive -e WORDPRESS_THEMES="responsive" --name wp --link mysql:mysql wp
  - sleep 15
  - docker logs wp
  - docker exec wp /bin/sh -c "apt-get update && apt-get install curl -y --no-install-recommends && curl -vf localhost:80"